# Generated by Django 6.0.3 on 2026-03-15 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheClient', models.CharField(max_length=50)),
                ('TheCompany', models.CharField(choices=[('JC Attorneys ', 'JC Attorneys '), ('Daniel Thiery', 'Daniel Thiery '), ('Wright Rose-Innes', 'Wright Rose-Innes'), ('Yammin Hammond Inc', 'Yammin Hammond Inc')], max_length=50)),
                ('TheFile', models.FileField(upload_to='documents')),
                ('TheUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
